version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Import casks from upstream
          command: |
            git config user.email 'ta2gch+circleci@users.noreply.github.com'
            git config user.name 'TANIGUCHI Masaya'
            git submodule update --init --remote
            bundle exec ruby cask2formula.rb
      - run:
          name: Push new formulae to origin/master
          command: git push git@github.com:ta2gch/homebrew-fonts
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 15 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build
