name: Ruby
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/ruby.y*ml
jobs:
  build:
    if: github.repository_owner == 'Homebrew' || !github.event.schedule
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Ruby 3
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Configure git
      run: |
        git config user.email 'ta2gch@gmail.com'
        git config user.name 'TANIGUCHI Masaya'
    - name: Convert and commit
      run: |
        git submodule update --init --remote
        bundle exec ruby cask2formula convert
        bundle exec ruby cask2formula commit
    - name: Clean Formula directory
      run: |
        comm -23 --nocheck-order <(ls -1 Formula) <(basename -a homebrew-cask-fonts/Casks/font/*/*) | xargs -I{} sh -c 'git rm ./Formula/{} && git commit -m "Remove {}"'
    - name: Publish to GitHub
      if: github.event_name != 'pull_request'
      env:
        TOKEN: ${{ secrets.PUSH_TOKEN }}
      run: |
        git push https://fgborges:${TOKEN}@github.com/Homebrew/homebrew-linux-fonts HEAD:master
