name: Ruby
on:
  schedule:
    - cron: 0 0 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Configure git
      run: |
        git config user.email 'fgborges@pm.me'
        git config user.name 'Fernando Garcia Borges'
    - name: Build and test with Rake
      run: |
        git submodule update --init --remote
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec ruby cask2formula
    - name: Clean Formula directory
      run: |
        comm -23 --nocheck-order <(ls -1 Formula) <(ls -1 homebrew-cask-fonts/Casks) | xargs -I{} sh -c 'git rm ./Formula/{} && git commit -m "Remove {}"'
    - name: Publish to GitHub
      env:
        TOKEN: ${{ secrets.PUSH_TOKEN }}
      run: |
        git push https://fgborges:${TOKEN}@github.com/Linuxbrew/homebrew-fonts HEAD:master
  
